/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "error-container": "#93000a",
        "outline-variant": "#59413c",
        "primary-container": "#ff6b4a",
        "primary-fixed": "#ffdad2",
        "on-background": "#d9e3f7",
        "outline": "#a88a83",
        "on-primary-container": "#661000",
        "surface-container-lowest": "#050e1c",
        "on-tertiary": "#253141",
        "inverse-primary": "#ae3115",
        "on-surface": "#d9e3f7",
        "background": "#0a1422",
        "surface-container-low": "#121c2a",
        "surface-container-highest": "#2c3545",
        "tertiary": "#bac7dc",
        "on-primary-fixed": "#3d0600",
        "on-error": "#690005",
        "surface-tint": "#ffb4a3",
        "tertiary-fixed": "#d6e3f8",
        "surface-container-high": "#212a39",
        "on-primary": "#630f00",
        "primary": "#ffb4a3",
        "on-surface-variant": "#e1bfb8",
        "secondary": "#f2bd74",
        "tertiary-container": "#8e9bae",
        "secondary-container": "#654200",
        "secondary-fixed": "#ffddb3",
        "on-tertiary-container": "#263343",
        "on-primary-fixed-variant": "#8c1900",
        "error": "#ffb4ab",
        "on-tertiary-fixed-variant": "#3b4858",
        "on-secondary-container": "#e3af67",
        "surface-container": "#16202f",
        "on-error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#624000",
        "inverse-on-surface": "#273140",
        "secondary-fixed-dim": "#f2bd74",
        "surface-variant": "#2c3545",
        "on-secondary-fixed": "#291800",
        "primary-fixed-dim": "#ffb4a3",
        "on-tertiary-fixed": "#0f1c2b",
        "surface-dim": "#0a1422",
        "surface": "#0a1422",
        "tertiary-fixed-dim": "#bac7dc",
        "inverse-surface": "#d9e3f7",
        "on-secondary": "#452b00",
        "surface-bright": "#303a49"
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      spacing: {
        "gutter-desktop": "2rem",
        "space-2xs": "0.25rem",
        "gutter-mobile": "1rem",
        "space-sm": "0.75rem",
        "space-xl": "2rem",
        "space-4xl": "6rem",
        "margin-mobile": "1.25rem",
        "margin-desktop": "4rem",
        "space-xs": "0.5rem",
        "space-2xl": "3rem",
        "space-lg": "1.5rem",
        "space-3xl": "4.5rem",
        "space-md": "1rem"
      },
      fontFamily: {
        "display-hero-mobile": ["Space Grotesk"],
        "body-sm": ["Plus Jakarta Sans"],
        "editorial-italic": ["Playfair Display"],
        "headline-lg-mobile": ["Space Grotesk"],
        "label-numeric": ["Space Grotesk"],
        "display-hero": ["Space Grotesk"],
        "editorial-italic-mobile": ["Playfair Display"],
        "headline-sm": ["Space Grotesk"],
        "body-lg": ["Plus Jakarta Sans"],
        "headline-md": ["Space Grotesk"],
        "body-md": ["Plus Jakarta Sans"],
        "headline-lg": ["Space Grotesk"],
        "label-caps": ["Space Grotesk"]
      },
      fontSize: {
        "display-hero-mobile": ["44px", { "lineHeight": "52px", "letterSpacing": "-0.03em", "fontWeight": "700" }],
        "body-sm": ["13px", { "lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "400" }],
        "editorial-italic": ["28px", { "lineHeight": "38px", "letterSpacing": "0.01em", "fontWeight": "400" }],
        "headline-lg-mobile": ["28px", { "lineHeight": "36px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-numeric": ["14px", { "lineHeight": "18px", "letterSpacing": "0.04em", "fontWeight": "500" }],
        "display-hero": ["72px", { "lineHeight": "80px", "letterSpacing": "-0.04em", "fontWeight": "700" }],
        "editorial-italic-mobile": ["20px", { "lineHeight": "28px", "letterSpacing": "0.01em", "fontWeight": "400" }],
        "headline-sm": ["18px", { "lineHeight": "26px", "letterSpacing": "0.02em", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "28px", "letterSpacing": "-0.01em", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-md": ["15px", { "lineHeight": "24px", "letterSpacing": "0em", "fontWeight": "400" }],
        "headline-lg": ["36px", { "lineHeight": "44px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-caps": ["11px", { "lineHeight": "14px", "letterSpacing": "0.14em", "fontWeight": "700" }]
      }
    }
  },
  plugins: [],
}